server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/student_payment_db
    password: '0885'
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: student-payment
